name: test

on:
    # Trigger workflow on "push to" or "pull request against" the master branch
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            target-ref:
                description: Target Commit/Branch/Tag
                required: true

jobs:
    ##
    # Setup project & cache dependencies
    ##
    deps:
        runs-on: ubuntu-latest
        steps:
            - name: '※ Prepare Node.js subsystem project dependencies'
              uses: catalyst-stack/github-actions/nodejs-subsystem-deps@master
              with:
                target-ref: ${{ github.event.inputs.target-ref }}

    ##
    # Run test suite in parallel
    ##
    test-lint:
        runs-on: ubuntu-latest
        needs: [deps]
        steps:
            - name: '※ Test lint'
              uses: catalyst-stack/github-actions/nodejs-subsystem-script@master
              with:
                target-ref: ${{ github.event.inputs.target-ref }}
                npm-script: test:lint

    test-types:
        runs-on: ubuntu-latest
        needs: [deps]
        steps:
            - name: '※ Test types'
              uses: catalyst-stack/github-actions/nodejs-subsystem-script@master
              with:
                target-ref: ${{ github.event.inputs.target-ref }}
                npm-script: test:types

    test-unit:
        runs-on: ubuntu-latest
        needs: [deps]
        steps:
            - name: '※ Test unit'
              uses: catalyst-stack/github-actions/nodejs-subsystem-script@master
              with:
                target-ref: ${{ github.event.inputs.target-ref }}
                npm-script: test:unit

    test-coverage:
        runs-on: ubuntu-latest
        needs: [deps]
        steps:
            - name: '※ Test coverage'
              uses: catalyst-stack/github-actions/nodejs-subsystem-script@master
              with:
                target-ref: ${{ github.event.inputs.target-ref }}
                npm-script: test:coverage
